export const autoCompleteData = [
    "Future Noodles Variety Pack",
    "Future Noodles Set",
    "Spicy Kimchi Noodles",
    "Yellow Curry Noodles",
    "Smoky Mushroom & Miso Noodles",
    "Organic Beansprouts",
    "Cucumbers",
    "Red Thai Chilis",
    "Organic Bokchoy",
    "Organic Beech Mushrooms",
    "Frozen Edamame",
    "Extra Soft Silken Tofu",
    "Spicy Kimchi in a Jar",
    "Frozen Gyoza (Potstickers)",
    "Roasted Sesame Seeds",
    "Colorful Chopstick Sets",
    "Handthrown Ramen Bowl",
    "Kitchen Timer",
    "Japanese Ramen Spoons",
    "The Ultimate Ramen Cooker Set",
];